In [140]:
####################################################################################################
# Maggie Horton
# CS-441 Summer 2021 
# Assignment 1
####################################################################################################
import numpy as np
import math
np.set_printoptions(precision=2) # for printing decimal values
####################################################################################################

# 1. using outer to make 10x10 multiplication table
nums = [1,2,3,4,5,6,7,8,9,10]
table = np.outer(nums,nums,out=None)
print('no. 1.\n'+str(table))

####################################################################################################

# 2. select the smaller table
smaller_table = table[3:7,3:7] # select rows & columns 4-7
print('\nno. 2.\n'+str(smaller_table))

####################################################################################################

# 3. create 4x4 array of values 1-16 using arange and reshape
import numpy as np
four_by_four = np.arange(start=1,stop=17,step=1).reshape(4,4) # specify start to begin @ 1
print('\nno. 3.\n'+str(four_by_four))

####################################################################################################

# 4. vectorized functions
def both_even(num1,num2):
  if (not num1%2) and (not num2%2): # even num % 2 = 0 so negate
    return True
  else: return False

v_both_even = np.vectorize(both_even) # vectorized function
bool_array = v_both_even(smaller_table,four_by_four) 
print('\nno. 4.\n'+str(bool_array))

####################################################################################################

# 5. return number of even numbers from array in q2 
even_count = 0
for num in np.nditer(smaller_table):
  if not(num%2):
    even_count+=1
print('\nno. 5. the array from q2 has '+str(even_count)+' even numbers.')

####################################################################################################

# 6. square root array
v_sqrt = np.vectorize(math.sqrt)
square_array = v_sqrt(four_by_four)
print('\nno. 6.\n' + str(square_array))

####################################################################################################

# 7. increment values on the diagonal of q1
incr_table = np.copy(table)
row_count = 0
for row in table:
  col_count = 0
  for col in row:
    if row_count == col_count:
      incr_table[row_count,col_count] = col + 1
    col_count += 1
  row_count += 1
print('\nno. 7.\n'+str(incr_table))

####################################################################################################

# 8. reverse each row of q1
rev_table = np.copy(table)
row_count = 0
for row in table:
  index = 0
  rev_index = table.shape[0] - 1
  for col in row:
    rev_table[row_count, rev_index] = table[row_count, index]
    index += 1
    rev_index -= 1
  row_count +=1
print('\nno. 8.\n'+str(rev_table))

####################################################################################################

# 9. 10x10 array of random floats, sorted
rand_float_list = np.random.uniform(low=0.0, high=10.0, size=(100))
rand_array = np.sort(rand_float_list).reshape(10,10)
print('\nno. 9.\n'+str(rand_array))

####################################################################################################

# 10. make 1D array containing the average of each row from array in q1
avg_array = np.empty([10,])
row_count = 0
for row in table:
  count = 0
  total = 0
  for col in row:
    total = total + col
    count += 1
  avg_array[row_count] = total/count
  row_count += 1
print('\nno. 10.\n'+str(avg_array))

####################################################################################################

# 11. do merge sort. use recursion with partition, split and hstack
def merge_sort(arr, left, right):
    if left < right:
        mid = (left + (right - 1)) // 2
        merge_sort(arr, left, mid)
        merge_sort(arr, mid + 1, right)
        merge(arr, left, mid, right)

def merge(arr, left, mid, right):
  left_len = mid - left + 1  
  right_len = right - mid
  left_arr = np.array(arr[left:left+left_len]) # left half
  right_arr = np.array(arr[mid + 1: mid + right_len + 1]) # right half
  
  p = left ; l = 0 ; r = 0  # position counters for arr, left_arr, right_arr   
        
  while (l < left_len) and (r < right_len) :
    sm_arr = np.empty(2,) # make small array
    sm_arr = np.hstack((left_arr[l], right_arr[r]))
    sm_arr.partition(0) # sorts the array of 2 items
    
    # increment position based on left & right vals
    if (left_arr[l] <= right_arr[r]): l += 1 
    else: r += 1
    
    new = slice(p, p+2) # make slice at current position for array
    arr[new] = sm_arr # replace the indices with the according small array
    p += 1 

  while l < left_len: # doing the same thing as for the next loop resulted in incorrect sorting
    arr[p] = left_arr[l]
    l += 1; p += 1

  while r < right_len:
    sp_arr = np.split(arr,[p]) # split at current position
    sp_arr[1][0] = right_arr[r] # replace value at current position, the first elem of second array
    arr = np.hstack(sp_arr) # combine array back together
    r += 1; p += 1

num_arr = np.array([6, 4, 1, 8, 0, 3, 10, 9, 2, 5, 7])
print('\nno. 11.\nunsorted:\n' + str(num_arr))

merge_sort(num_arr, 0, num_arr.size - 1)
print('\nsorted:\n'+str(num_arr))



no. 1.
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

no. 2.
[[16 20 24 28]
 [20 25 30 35]
 [24 30 36 42]
 [28 35 42 49]]

no. 3.
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

no. 4.
[[False  True False  True]
 [False False False False]
 [False  True False  True]
 [False False False False]]

no. 5. the array from q2 has 12 even numbers.

no. 6.
[[1.   1.41 1.73 2.  ]
 [2.24 2.45 2.65 2.83]
 [3.   3.16 3.32 3.46]
 [3.61 3.74 3.87 4.  ]]

no. 7.
[[  2   2   3   4   5   6   7   8   9  10]
 [  2   5   6   8  10  12  14  16  18  20]
 [  3   6  10  12  15  18  21  24  27  30]
 [  4   8  12  17  20 